export const tabItems = [
  {
    key: 0,
    path: " /assets/instagram3.png",
    title: "Instagram Posts",
    description: "https://www.instagram.com/",
    hasImg: true,
    itHasImg: false,
    img: "/assets/bubble-chat3.png",
  },
  {
    key: 1,
    path: " /assets/youtube3.png",
    title: "YouTube Channel YY ",
    description: "https://www.instagram.com/",
    hasImg: false,
    itHasImg: false,
    img: "",
  },
  {
    key: 2,
    path: " /assets/facebook.svg",
    title: "Anil Kapoor Posts 2",
    description: "https://www.instagram.com/",
    hasImg: false,
    itHasImg: true,
    img: "/assets/target-023.png",
  },
  {
    key: 3,
    path: " /assets/twitter3.png",
    title: "Tweet-Narendra Modi",
    description: "https://www.instagram.com/",
    hasImg: false,
    itHasImg: false,
    img: "",
  },
  {
    key: 4,
    path: " /assets/pinterest3.png",
    title: "Pinterest - Images ",
    description: "https://www.instagram.com/",
    hasImg: false,
    itHasImg: false,
    img: "",
  },
  {
    key: 5,
    path: " /assets/reddit3.png",
    title: "Reddit-Hello",
    description: "https://www.instagram.com/",
    hasImg: false,
    itHasImg: false,
    img: "",
  },
  {
    key: 6,
    path: " /assets/linkedin3.png",
    title: "Linkedin-New Post",
    description: "https://www.instagram.com/",
    hasImg: false,
    itHasImg: false,
    img: "",
  },
];
