export const cardData = [
  {
    title: "Social Media",
    emoji: "/assets/thumbs-up3.png",
    links: [
      {
        name: "Instagram Posts",
        url: "https://www.instagram.com/",
        icon: " /assets/instagram3.png",
        hasImg: true,
        itHasImg: false,
        img: "/assets/bubble-chat3.png",
      },
      {
        name: "YouTube Channel YY",
        url: "https://www.youtube.com/",
        icon: " /assets/youtube3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Anil Kapoor Posts 2",
        url: "https://www.instagram.com/",
        icon: " /assets/facebook.svg",
        hasImg: false,
        itHasImg: true,
        img: "/assets/target-023.png",
      },
      {
        name: "Tweet - Narendra Modi",
        url: "https://twitter.com/",
        icon: " /assets/twitter3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Pinterest - Images",
        url: "https://www.pinterest.com/",
        icon: " /assets/pinterest3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Reddit - Hello",
        url: "https://www.reddit.com/",
        icon: " /assets/reddit3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "LinkedIn - New Post",
        url: "https://www.linkedin.com/",
        icon: " /assets/linkedin3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
    ],
  },
  {
    title: "Personal",
    emoji: "/assets/green-heart3.png",
    links: [
      {
        name: "Instagram Posts",
        url: "https://www.instagram.com/",
        icon: " /assets/instagram3.png",
        hasImg: true,
        itHasImg: false,
        img: "/assets/bubble-chat3.png",
      },
      {
        name: "YouTube Channel YY",
        url: "https://www.youtube.com/",
        icon: " /assets/youtube3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Anil Kapoor Posts 2",
        url: "https://www.instagram.com/",
        icon: " /assets/facebook.svg",
        hasImg: false,
        itHasImg: true,
        img: "/assets/target-023.png",
      },
      {
        name: "Tweet - Narendra Modi",
        url: "https://twitter.com/",
        icon: " /assets/twitter3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Pinterest - Images",
        url: "https://www.pinterest.com/",
        icon: " /assets/pinterest3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Reddit - Hello",
        url: "https://www.reddit.com/",
        icon: " /assets/reddit3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "LinkedIn - New Post",
        url: "https://www.linkedin.com/",
        icon: " /assets/linkedin3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
    ],
  },
  {
    title: "Trending",
    emoji: "/assets/nazar-amulet3.png",
    links: [
      {
        name: "Instagram Posts",
        url: "https://www.instagram.com/",
        icon: " /assets/instagram3.png",
      },
      {
        name: "YouTube Channel YY",
        url: "https://www.youtube.com/",
        icon: " /assets/youtube3.png",
      },
      {
        name: "Anil Kapoor Posts 2",
        url: "https://www.instagram.com/",
        icon: " /assets/facebook.svg",
      },
      {
        name: "Tweet - Narendra Modi",
        url: "https://twitter.com/",
        icon: " /assets/twitter3.png",
      },
      {
        name: "Pinterest - Images",
        url: "https://www.pinterest.com/",
        icon: " /assets/pinterest3.png",
      },
      {
        name: "Reddit - Hello",
        url: "https://www.reddit.com/",
        icon: " /assets/reddit3.png",
      },
      {
        name: "LinkedIn - New Post",
        url: "https://www.linkedin.com/",
        icon: " /assets/linkedin3.png",
      },
    ],
  },
  {
    title: "My Favorites",
    emoji: "/assets/wrapped-gift3.png",
    links: [
      {
        name: "Instagram Posts",
        url: "https://www.instagram.com/",
        icon: " /assets/instagram3.png",
        hasImg: true,
        itHasImg: false,
        img: "/assets/bubble-chat3.png",
      },
      {
        name: "YouTube Channel YY",
        url: "https://www.youtube.com/",
        icon: " /assets/youtube3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Anil Kapoor Posts 2",
        url: "https://www.instagram.com/",
        icon: " /assets/facebook.svg",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Tweet - Narendra Modi",
        url: "https://twitter.com/",
        icon: " /assets/twitter3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Pinterest - Images",
        url: "https://www.pinterest.com/",
        icon: " /assets/pinterest3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "Reddit - Hello",
        url: "https://www.reddit.com/",
        icon: " /assets/reddit3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
      {
        name: "LinkedIn - New Post",
        url: "https://www.linkedin.com/",
        icon: " /assets/linkedin3.png",
        hasImg: false,
        itHasImg: false,
        img: "",
      },
    ],
  },
];

export const menuItems = [
  {
    key: 0,
    src: "/assets/briefcase3.png",
    title: "Atomic House",
  },
  {
    key: 1,
    src: "/assets/inbox.svg",
    title: "Inbox",
  },
  {
    key: 2,
    src: "/assets/settings3.png",
    title: "Settings",
  },
  {
    key: 3,
    src: "/assets/dashboard3.png",
    title: "All Brands",
  },
  {
    key: 4,
    src: "/assets/anger-symbol3.png",
    title: "Website Design",
  },
  {
    key: 5,
    src: "/assets/mobile3.png",
    title: "Mobile Design",
  },
  {
    key: 6,
    src: "/assets/folder.y3.png",
    title: "Folder",
  },
  {
    key: 7,
    src: "/assets/folder.r3.png",
    title: "Folder",
  },
];
